services:
  - type: web
    name: nexus-backend
    env: python
    region: ohio
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString

databases:
  - name: nexus-db
    region: ohio
    plan: free
